name: Deploy to Digital Ocean Droplet

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Download and run the deployment script
            cd /tmp
            curl -O https://raw.githubusercontent.com/VictorJuez/TaskTracker/main/scripts/deploy.sh
            chmod +x deploy.sh
            ./deploy.sh
