name: Deploy to Digital Ocean Droplet

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Check if this is initial setup or update
            if [ ! -d "/var/www/tasktracker" ]; then
              echo "🚀 Detected new droplet - running bootstrap..."
              cd /tmp
              curl -O https://raw.githubusercontent.com/VictorJuez/TaskTracker/main/scripts/bootstrap.sh
              chmod +x bootstrap.sh
              ./bootstrap.sh
            fi

            # Download and run the deployment script
            cd /tmp
            curl -O https://raw.githubusercontent.com/VictorJuez/TaskTracker/main/scripts/deploy.sh
            chmod +x deploy.sh
            ./deploy.sh
